version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - misspell
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default-excludes: false

formatters:
  enable:
    - goimports
