package main

import armerrors "github.com/scullxbones/armature/internal/errors"

func init() {
	armerrors.Register("AMEND-1")
	armerrors.Register("ASSIGN-1")
	armerrors.Register("BOOTSTRAP-1")
	armerrors.Register("COMPLETION-1")
	armerrors.Register("CONFIRM-1")
	armerrors.Register("CONTEXT-HISTORY-1")
	armerrors.Register("CONTEXT-REPORT-1")
	armerrors.Register("CREATE-1")
	armerrors.Register("DAG-1")
	armerrors.Register("DECISION-1")
	armerrors.Register("DOCTOR-1")
	armerrors.Register("GATE-1")
	armerrors.Register("HEARTBEAT-1")
	armerrors.Register("IMPORT-1")
	armerrors.Register("LINK-1")
	armerrors.Register("LIST-1")
	armerrors.Register("LOG-1")
	armerrors.Register("MATERIALIZE-1")
	armerrors.Register("MERGED-1")
	armerrors.Register("NOTE-1")
	armerrors.Register("PUSH-OPS-1")
	armerrors.Register("REOPEN-1")
	armerrors.Register("REPARENT-1")
	armerrors.Register("SCOPE-DELETE-1")
	armerrors.Register("SCOPE-RENAME-1")
	armerrors.Register("SHOW-1")
	armerrors.Register("SOURCES-1")
	armerrors.Register("STATS-1")
	armerrors.Register("SYNC-1")
	armerrors.Register("TUI-1")
	armerrors.Register("UNASSIGN-1")
	armerrors.Register("UNLINK-1")
	armerrors.Register("VALIDATE-1")
	armerrors.Register("VERSION-1")
	armerrors.Register("WORKER-INIT-1")
	armerrors.Register("WORKERS-1")
	armerrors.Register("WORKTREE-1")
}
